version: '3'

services:

  takesmyeggs:
    container_name: takesmyeggs
    build: .
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=PathPrefixStrip:/takesmyeggs
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - web

networks:
  web:
    external: true